spring:
  application:
    name: SpringAPI
    
management:
  security:
    enabled: false
    
server:
  port: ${PORT:8090}

#datasource:
#  mysql:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://115.68.47.165:3306/edu
#    username: root
#    password: Paasta@2019


# Discovery Server Access

---
spring:
  profiles: local

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: ${spring.cloud.client.hostname}

---
spring:
  profiles: dev

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://springeureka.sys.pas.martin-bw-piv.net/eureka/
  instance:
    hostname: ${spring.cloud.client.hostname}
